### ISSUE TITLE
CSS issues with course info on mobile

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-course-hugo-theme#93] opened 2021-04-28 15:53 UTC
### Screenshot or Screencast

![Screenshot from 2021-04-28 11-52-04](https://user-images.githubusercontent.com/863262/116434332-542f4e80-a818-11eb-8fed-c6a1c07102b1.png)

**Comment by pdpinch** [comment] 2021-04-28 16:24
@gumaerc did you have a PR to fix this?

**Comment by gumaerc** [comment] 2021-04-28 16:28
This is a duplicate of https://github.com/mitodl/ocw-course-hugo-theme/issues/86, and yes it will be fixed by https://github.com/mitodl/ocw-course-hugo-theme/pull/87

**Comment by pdpinch** [comment] 2021-05-27 14:05
Fixed by #87

**Closed as completed by pdpinch** 2021-05-27 14:05 UTC
Labels: bug
